image: ruby:3.2-bullseye

stages:
  - build
  - deploy
  - mirror

variables:
  JEKYLL_ENV: production
  BUNDLE_PATH: vendor/bundle
  PAGES_DIR: public
  GIT_DEPTH: 0  # Full clone for build, but not used for GitHub mirroring

before_script:
  - apt-get update -qq && apt-get install -y nodejs
  - gem install bundler
  - bundle install

build:
  stage: build
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  script:
    - bundle exec jekyll build -d $PAGES_DIR
  artifacts:
    paths:
      - $PAGES_DIR

pages:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  script:
    - echo "Deploying to GitLab Pages"
  artifacts:
    paths:
      - $PAGES_DIR

mirror_to_github:
  stage: mirror
  rules:
    rules:
      - if: '$CI_COMMIT_BRANCH == "current"'
        when: always
      - if: '$CI_COMMIT_BRANCH == "main"'
        when: always

  script:
    - echo "Mirroring the Git repo (source code) to GitHub..."
    - git config --global user.name "GitLab CI"
    - git config --global user.email "ci@example.com"
    - export GITHUB_REPO="https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/${GITHUB_USER}/gl-copy-site.git"
    - git remote add github "$GITHUB_REPO"
    - git remote -v
    - git push --force github HEAD:refs/heads/mirror

