name: Auto-Merge Mirror to Main

on:
  push:
    branches:
      - mirror

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Auto-merge mirror -> main
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git fetch origin mirror
          git checkout main
          git merge --ff-only mirror
          git push origin main
