name: Auto Merge Mirror to Main

on:
  workflow_dispatch:
  push:
    branches:
      - mirror

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Fetch main and mirror branches
        run: |
          git fetch origin main
          git fetch origin mirror

      - name: Checkout main branch
        run: git checkout main

      - name: Merge mirror into main (fast-forward only)
        run: git merge --ff-only origin/mirror

      - name: Push changes to main
        run: git push origin main

