name: Notify on PR
on:
  pull_request:
    types: [opened, reopened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification (example)
        run: echo "New Pull Request: ${{ github.event.pull_request.html_url }}"
