name: PR Slack Notify

on:
  pull_request:
    types: [opened, reopened, ready_for_review]
    branches:
      - mirror

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send PR notification to Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          pr_title="${{ github.event.pull_request.title }}"
          pr_url="${{ github.event.pull_request.html_url }}"
          pr_author="${{ github.event.pull_request.user.login }}"
          message="New PR opened by *${pr_author}*: <${pr_url}|${pr_title}>"

          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\": \"$message\"}" \
            $SLACK_WEBHOOK_URL
