# .github/workflows/trigger-gitlab.yml
name: Trigger GitLab sync

on:
  push:
    branches:
      - mirror

jobs:
  trigger-gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitLab pipeline
        run: |
          curl -X POST \
            -F token=$GL_TRIGGER_TOKEN \
            -F ref=current \
            https://gitlab.com/api/v4/projects/68146715/trigger/pipeline
        env:
          GL_TRIGGER_TOKEN: ${{ secrets.GITLAB_TRIGGER_TOKEN }}
